apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-blood-bowl-league-manager-db-pvc
  namespace: blood-bowl-league-manager
spec:
  selector:
    matchLabels:
      volume: blood-bowl-league-manager-postgres
  accessModes: [ "ReadWriteMany" ]
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi